alias gs='git status'
alias gp='git pull'
alias ga='git add . --all'
alias gm='git merge --no-ff'
alias gc='git changelog'
alias gg='git graph'
alias gcm='git checkout master'
alias gsm='git submodule update --init --recursive'
alias gup='git pull --rebase --prune $argv; and gsm'

alias eh='sudo vim /etc/hosts'
alias sosaria='ssh root@192.241.183.18'
alias ..='cd ..'
