alias gs='git status'
alias gp='git pull'
alias ga='git add . --all'
alias gap='git add -p'
alias gm='git merge --no-ff'
alias gc='git changelog'
alias gg='git graph'
alias gcm='git checkout master'
alias gsm='git submodule update --init --recursive'
alias gup='git pull --rebase --prune $argv; and gsm'
alias hash='git rev-parse --short HEAD | pbcopy'
alias thq='ssh tictailhq.com'
alias ops='ssh ops.production.tictail.io'

alias eh='sudo vim /etc/hosts'
alias ..='cd ..'
