##Aliases
alias grd='sudo grunt'
alias grp='sudo grunt prod-watch'
alias gs='git status'
alias gp='git pull'
alias ga='git add . --all'
alias gcm='git checkout master'
alias ccui='cd ~/Projects/vcs.checkout-ui/'
alias eh='sudo gedit /etc/hosts'
git config --global alias.changelog 'log --pretty=oneline --abbrev-commit --no-merges'
alias clb='git changelog beta/1.2.0..master'
alias cls='git changelog stable/1.1.0..master'
